#!/bin/bash

#  salt-minion-setup - configure Salt minion master
#  Copyright (c)  2014 - 2015  Mika Tapojärvi <mika.tapojarvi@embelin.fi>.
#
#  Distributed under the MIT License, see file LICENSE.
#
#  This file is part of toolscripts.

shortusage()
{
    echo "Salt minion configuration."
    echo "usage: `basename $0` [ <no params> | -h | -i <ip> | -m <id> | -v ]"
    echo "       `basename $0` [ --help ]"
    echo "       `basename $0` [ --version ]"
}


usage()
{
    echo -e "\n\n"
    echo "  <no parameters>            Display short usage."
    echo "  -h   --help                This help text."
    echo "  -i <ip>                    Set Salt master IP address and restart minion."
    echo "  -m <id>                    Set Salt minion id string."
    echo "  -v   --version             Display script version."
    echo -e "\n  Example: `basename $0` -i 82.23.1.18 -m `hostname`"
}


show_version()
{
    echo "`basename $0` version 0.3"
}


##################################################################################
#      main of salt-minion-setup                                                 #
##################################################################################

if [[ "$1" == "" ]];
then
    shortusage
    exit 0
fi


#
# Clear variables
IPADDRESS=""
MINIONID=""
MINIONCONF=/etc/salt/minion
MINIONIDFILE=/etc/salt/minion_id
MASTEREXISTS=0
MINIONIDEXISTS=0


while getopts 'hi:m:v-:-' opt;
do
    case $opt in
    h)  shortusage; usage; exit 0;;
    i)  IPADDRESS="${OPTARG}";;
    m)  MINIONID="${OPTARG}";;
    v)  show_version; exit 0;;
    -)
        case "${OPTARG}" in
            help)
                shortusage
                usage
                exit 0
                ;;

            version)
                show_version
                exit 0
                ;;

            *)
                echo "Unknown option"
                ;;
        esac
    esac
done
shift $((OPTIND - 1));


if [ -f $MINIONCONF ];
then
    echo "Current Salt master IP/domain configuration for this minion:"
    grep ^master: $MINIONCONF
    if [ $? -eq 1 ];
    then
        echo -e "\nNO MASTER SET!!\n"
    else
        MASTEREXISTS=1

        # If configuration was done with old version of salt-minion-setup,
        # it might be that there are accidentally more than one lines of
        # master configurations... The first one is in right place, two
        # others can be cleaned.
        AMOUNT=`grep ^master: $MINIONCONF | wc -l`
        if [ $AMOUNT -gt 1 ];
        then
            sed -i '0,/^master:/! s/^master:.*//' $MINIONCONF
        fi

    fi

    echo "Current Salt minion id:"
    grep ^id: $MINIONCONF
    if [ $? -eq 1 ];
    then
        echo -e "\nNO ID SET!!\n"
    else
        MINIONIDEXISTS=1
    fi
else
    echo "Minion config file not found at $MINIONCONF!"

    dpkg -l salt-minion > /dev/null 2> /dev/null
    if [ $? -eq 1 ];
    then
        echo "salt-minion package is missing! Install it first."
        exit 1
    fi
fi

if [ `id -u` -eq 0 ];
then
    if [ -z "$IPADDRESS" ];
    then
        echo "IP address/domain missing!"
    else
        echo "Changing Salt master to: $IPADDRESS."
        if [ $MASTEREXISTS -eq 0 ];
        then
            sed -i "s/#master:.*/master: $IPADDRESS/" $MINIONCONF
        else
            sed -i "s/^master:.*/master: $IPADDRESS/" $MINIONCONF
        fi
    fi

    if [ ! -z "$MINIONID" ];
    then
        echo "Changing minion id to: $MINIONID"
        if [ $MINIONIDEXISTS -eq 0 ];
        then
            sed -i "s/#id:.*/id: $MINIONID/" $MINIONCONF
        else
            sed -i "s/^id:.*/id: $MINIONID/" $MINIONCONF
        fi

        # If Salt has minion_id file, change that too.
        if [ -f $MINIONIDFILE ];
        then
            echo "$MINIONID" > $MINIONIDFILE
        fi
    fi


    echo "Restarting salt-minion:"
    service salt-minion restart
else
    echo -e "\nYou should become root to be able to change this."
    echo "You currently have:"
    echo "- \$USER: $USER"
    echo "- id -u: `id -u`"
    exit 2
fi
