#!/bin/bash

#  salt-minion-setup - configure Salt minion master
#  Copyright (c)  2014  Mika Tapojärvi <mika.tapojarvi@embelin.fi>.
#
#  Distributed under the MIT License, see file LICENSE.
#
#  This file is part of toolscripts.

shortusage()
{
    echo "Salt minion configuration."
    echo "usage: `basename $0` [ <no params> | -h | -i <ip> | -v ]"
    echo "       `basename $0` [ --help ]"
    echo "       `basename $0` [ --version ]"
}


usage()
{
    echo -e "\n\n"
    echo "  <no parameters>            Display short usage."
    echo "  -h   --help                This help text."
    echo "  -i <ip>                    Set Salt master IP address and restart minion"
    echo "  -v   --version             Display script version."
    echo -e "\n  Example: `basename $0` -i 82.23.1.18"
}


show_version()
{
    echo "`basename $0` version 0.1"
}


##################################################################################
#      main of salt-minion-setup                                                 #
##################################################################################

if [[ "$1" == "" ]];
then
    shortusage
    exit 0
fi


#
# Clear variables
IPADDRESS=""
MINIONCONF=/etc/salt/minion

while getopts 'hi:v-:-' opt;
do
    case $opt in
    h)  shortusage; usage;;
    i)  IPADDRESS="${OPTARG}";;
    v)  show_version; exit 0;;
    -)
        case "${OPTARG}" in
            help)
                shortusage
                usage
                exit 0
                ;;

            version)
                show_version
                exit 0
                ;;

            *)
                echo "Unknown option"
                ;;
        esac
    esac
done
shift $((OPTIND - 1));


if [ -f $MINIONCONF ];
then
    echo "Current Salt master IP/domain configuration for this minion:"
    grep master: $MINIONCONF
else
    echo "Minion config file not found at $MINIONCONF!"

    dpkg -l salt-minion > /dev/null 2> /dev/null
    if [ $? -eq 1 ];
    then
        echo "salt-minion package is missing! Install it first."
        exit 1
    fi
fi

if [ -z "$IPADDRESS" ];
then
    echo "IP address/domain missing!"
fi

if [ "$USER" == "root" ];
then
    echo "Changing it to: master: $IPADDRESS."
    sed -i "s/.*master:.*/master: $IPADDRESS/" $MINIONCONF

    echo "Restarting salt-minion:"
    service salt-minion restart
else
    echo -e "\nYou should become root to be able to change this, you are now [$USER]."
    exit 2
fi
